### ISSUE TITLE
removed from chrome web store

### ISSUE THREAD

**Issue by erenseymen** [seferov/yemeksepeti-extension#4]
why?

**Comment by seferov** [comment]
Yemeksepeti requested to take it down from web store because of trademark infringement. It can be re-published under a different name though.

**Comment by iercan** [comment]
I added it to store by removing brand name from title. 
https://chrome.google.com/webstore/detail/joker-bek%C3%A7isi/mbjnaohagdfmamojbcginnhnmlgnhkip

**Comment by seferov** [comment]
@ibotheperfect 👍
